### ISSUE TITLE
It does not work

### ISSUE THREAD

**Issue by programmerlexi** [NeuralNine/ai-car-simulation#1]
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "newcar.py", line 248, in <module>
    config = neat.config.Config(neat.DefaultGenome,
AttributeError: module 'neat' has no attribute 'config'

**Comment by warmpigman** [comment]
pip install neat-python

**Comment by arch-user-france1** [comment]
You're not having the correct version of neat. @NeuralNine why do you post trash - it doesn't even have a requirements file

**Comment by arch-user-france1** [comment]
I'm running into the same dude. This is trash, nothing else

**Comment by NeuralNine** [comment]
> I'm running into the same dude. This is trash, nothing else

I recommend you use the search engine of your choice to look up your problems, before you comment that something is "trash".

The reason for this error message is that the pip module, which was installed is probably 'neat'. Even though the name is 'neat' when importing, the necessary pip module is called 'neat-python'.

**Comment by arch-user-france1** [comment]
Dude I recommend you to make a requirements.txt file that's why I mean it is trash :D
